### ISSUE TITLE
Plugin caused a crash

### ISSUE THREAD

**Issue by gorjious** [florianpircher/GutenTag#13]
Happy to see this plugin, it looks like it will be very useful. 

I tried to install in G2 and G3, and I get the following errors:

<img width="595" alt="Screenshot 2021-02-02 at 13 43 49" src="https://user-images.githubusercontent.com/23149420/106660544-62453a00-655d-11eb-9aab-56127ff04141.png">
<img width="630" alt="Screenshot 2021-02-02 at 13 45 35" src="https://user-images.githubusercontent.com/23149420/106660550-63766700-655d-11eb-9613-22adbd6f5cb3.png">

**Comment by florianpircher** [comment]
Glyphs 2 does not have tags, so Guten Tag can’t work there.

The Glyphs 3 error message indicates to me that you are using a Python version older than 3.8. Are there other plugins you use that rely on you using an old Python version? If not, please install Python from the Plugin Manager and select it in Glyphs preferences, like so:

<img width="912" alt="Window → Plugin Manager → Modules → Python" src="https://user-images.githubusercontent.com/3776198/106666019-52eade80-65a7-11eb-9cd4-7e6c409185a1.png">

<img width="878" alt="Preferences… → Addons → Python version: 3.8.2 (Glyphs)" src="https://user-images.githubusercontent.com/3776198/106666074-6433eb00-65a7-11eb-8fd0-215fecc75303.png">

Thank you for the report and thanks for trying Guten Tag. It is still in beta, but I would like to polish it over the week and add it to the Plugin Manager which allows new versions to be installed automatically.

**Comment by gorjious** [comment]
Ah, works now. Thanks, I appreciate the reply.
