### ISSUE TITLE
Crash when opening a Glyphs file

### ISSUE THREAD

**Issue by jenskutilek** [florianpircher/GutenTag#29]
I just got this crash when opening a Glyphs file. But I cannot reproduce it again.

```
Traceback (most recent call last):

  File "GlyphsApp/__init__.py", line 1333, in callback_

  File "plugin.py", line 334, in update
    self.tokenField.setPlaceholderString_("")

AttributeError: 'GSBackgroundLayer' object has no attribute 'setPlaceholderString_'

App:3.0.3-3081 Plugin:1.0.0-6
```

**Comment by florianpircher** [comment]
These seems odd considering that the plugin never interacts with the background layer. I will look into it. Thank you for reporting, could you also tell me what macOS version you are using?

**Comment by jenskutilek** [comment]
Thanks! I'm on macOS 10.13.6.

**Comment by florianpircher** [comment]
> But I cannot reproduce it again.

Did it ever occur again? I can not reproduce this bug.

**Comment by jenskutilek** [comment]
I had an idea that maybe it happens when a background layer is active when a font is being opened, but I can't reproduce it. Weird.

**Comment by florianpircher** [comment]
While I still have no idea what might have caused this error, I think (hope) that the release today fixes it.
