### ISSUE TITLE
Feature proposal : Tag Panel

### ISSUE THREAD

**Issue by HugoJourdan** [florianpircher/GutenTag#33]
Hey Florian !
I've developed a script that displays all glyphs from a tag in the UI for easier navigation and content preview. While it's functional, I think integrating a feature similar to the "Glyph Panel" into GutenTag could be really useful. Specifically, the feature could use a PopUpButton to filter glyphs based on tags. 

![Screenshot 2023-09-01 at 09 46 02](https://github.com/florianpircher/GutenTag/assets/76793951/86efdcb1-6661-40ce-9d52-f005845eb1a5)

**Comment by florianpircher** [comment]
Hi, thanks for this proposal. It might be interesting to combine such a feature with other glyph properties; not just tags. Maybe that would belong into Glyphs directly.

**Comment by florianpircher** [comment]
This is still interesting, but I would like it to be more general and made separately. Closing for now.
